//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {// [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }
        [Required(ErrorMessage = "ID Không Được Trống")]
        public int IDCus { get; set; }
        [Required(ErrorMessage = "Tên Không Được Trống")]
        public string NameCus { get; set; }
        [Required(ErrorMessage = "Số Điện Thoại Không Được Trống")]
        [RegularExpression(@"^([0])?[1-9][0-9]{8}$", ErrorMessage = "Số Điện Thoại Không Hợp Lệ")]
        public string PhoneCus { get; set; }
        [Required(ErrorMessage = "E-mail Không Được Trống")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail không hợp lệ")]
        public string EmailCus { get; set; }
    
      //  [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
    }
}
